// <auto-generated />
namespace FamousQuoteQuizGame.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserGameInfoSecondTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserGameInfoSecondTry));
        
        string IMigrationMetadata.Id
        {
            get { return "201701150904199_UserGameInfo-SecondTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
